services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=authdb
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
